const events = [
  {
    title: "AI & Machine Learning Workshop",
    category: "academic",
    startDate: new Date("2026-04-10"),
    endDate: new Date("2026-04-10"),
    startTime: "10:00",
    endTime: "14:00",
    description: "Hands-on workshop on AI and ML basics.",
    tags: ["AI", "ML", "Workshop"],
    maxAttendees: 120,
  },
  {
    title: "Annual Cultural Fest",
    category: "cultural",
    startDate: new Date("2026-04-20"),
    endDate: new Date("2026-04-22"),
    startTime: "09:00",
    endTime: "20:00",
    description: "Three-day cultural festival with music and dance.",
    tags: ["Dance", "Music", "Fest"],
    maxAttendees: 500,
  },
  {
    title: "Cricket Tournament",
    category: "sports",
    startDate: new Date("2026-05-05"),
    endDate: new Date("2026-05-07"),
    startTime: "08:00",
    endTime: "17:00",
    description: "Inter-college cricket competition.",
    tags: ["Cricket", "Tournament"],
    maxAttendees: 300,
  },
  {
    title: "Career Guidance Seminar",
    category: "career",
    startDate: new Date("2026-04-15"),
    endDate: new Date("2026-04-15"),
    startTime: "11:00",
    endTime: "13:00",
    description: "Industry experts guide students about tech careers.",
    tags: ["Career", "Seminar"],
    maxAttendees: 200,
  },
  {
    title: "React Bootcamp",
    category: "academic",
    startDate: new Date("2026-04-12"),
    endDate: new Date("2026-04-13"),
    startTime: "10:00",
    endTime: "16:00",
    description: "Learn React from basics to advanced.",
    tags: ["React", "Frontend"],
    maxAttendees: 150,
  },
  {
    title: "Photography Contest",
    category: "cultural",
    startDate: new Date("2026-04-25"),
    endDate: new Date("2026-04-25"),
    startTime: "09:00",
    endTime: "15:00",
    description: "Photography competition for students.",
    tags: ["Photography", "Art"],
    maxAttendees: 80,
  },
  {
    title: "Football Championship",
    category: "sports",
    startDate: new Date("2026-05-10"),
    endDate: new Date("2026-05-12"),
    startTime: "07:00",
    endTime: "18:00",
    description: "University football championship.",
    tags: ["Football", "Sports"],
    maxAttendees: 250,
  },
  {
    title: "Resume Building Workshop",
    category: "career",
    startDate: new Date("2026-04-18"),
    endDate: new Date("2026-04-18"),
    startTime: "14:00",
    endTime: "17:00",
    description: "Learn to create professional resumes.",
    tags: ["Resume", "Placement"],
    maxAttendees: 100,
  },
  {
    title: "Hackathon 2026",
    category: "academic",
    startDate: new Date("2026-06-01"),
    endDate: new Date("2026-06-02"),
    startTime: "09:00",
    endTime: "09:00",
    description: "24 hour coding hackathon.",
    tags: ["Coding", "Hackathon"],
    maxAttendees: 180,
  },
  {
    title: "Talent Show",
    category: "cultural",
    startDate: new Date("2026-04-30"),
    endDate: new Date("2026-04-30"),
    startTime: "18:00",
    endTime: "21:00",
    description: "Students perform singing, dancing and comedy.",
    tags: ["Talent", "Music"],
    maxAttendees: 220,
  },
];

module.exports = events;
